language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn test --watchAll=false
  - yarn build
on:
  branch: main
deploy:
  provider: heroku
  api_key: 52f21c14-e4c4-491c-999c-2a83510b1a59
  app: devopsa4


redis:
  image: redis
  restart: always
  ports:
    - 16379:6379
